### ISSUE TITLE
[Bug] User interface is partially obstructed by the navigation bar in landscape orientation

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [Ayagikei/LifeUp#42] opened 2022-09-25 15:43 UTC
# Describe the bug
I wouldn't categorized this as a bug, but rather as a design mistake or an oversight: The onscreen navigation bar overlaps some buttons in the app when in landscape orientation, at least on phones, making it hard to click things behind it.

## To Reproduce
1. Adjust your default navigation method to something other than Android 10's gesture navigation, like the classic 3-button method (◀️⏺️⏹️)
2. Go into the app and rotate your device sideways

## Expected behavior
Ideally, *nothing* should be obstructed like this.

## Screenshots
If applicable, add screenshots to help explain your problem:
![Screenshot_20220925-005837](https://user-images.githubusercontent.com/92757918/192151351-bf71ae01-1921-4a3b-86ba-e2cf503e7db5.png)

## Environments and Version (please complete the following information):
 - Device: **Moto z4**
 - OS: **Android 10**
 - Version: **1.90.5**

# Additional context
+ This does not occur with gesture navigation, due to being positioned differently on-screen.
+ This occurs regardless of the Material You toggle

**Comment by Ayagikei** [comment] 2022-09-25 17:57
Got it. **Thanks for the feedback!**

We will try to fix this issue in the next release.

**Comment by UsernamesAreNotMyThing** [comment] 2022-12-16 19:20
This still occurs on the Synthesis and Achievement List pages, but in portrait orientation instead. Easiest to notice if you scroll to the very bottom of the page.

**Comment by Ayagikei** [comment] 2022-12-17 11:49
> This still occurs on the Synthesis and Achievement List pages, but in portrait orientation instead. Easiest to notice if you scroll to the very bottom of the page.

Thanks for the feedback again!
We will check it.

**Comment by Ayagikei** [comment] 2023-03-26 11:08
The issue should be already fixed in v1.91.0.

**Closed by Ayagikei** 2023-03-26 11:08 UTC
Labels: bug, working on it

**Comment by UsernamesAreNotMyThing** [comment] 2023-05-11 14:35
Still occurring on the Synthesis page.

**Comment by Ayagikei** [comment] 2023-05-11 15:00
> Still occurring on the Synthesis page.

Get it, and we will recheck it.

**Comment by Ayagikei** [comment] 2023-05-13 09:05
> Still occurring on the Synthesis page.

It seems that I can't reproduce this problem with a MIUI mobile phone in landscape orientation.

Could you re-provide device information and screenshots of the problem?

**Comment by UsernamesAreNotMyThing** [comment] 2023-05-13 17:24
What I meant is the problem occurs there in **portrait** orientation.

**Comment by Ayagikei** [comment] 2023-05-13 17:42
> What I meant is the problem occurs there in **portrait** orientation.

We tested it on ColorOS13 and MIUI13 in portrait orientation but still did not reproduce the problem.

If the reproduced device is still the Moto z4 mentioned in the issue, please provide a screenshot of the problem that the UI is still blocked when the page already slides to the bottom.

We will test it again with AOSP (pixel emulator) later.

**Comment by UsernamesAreNotMyThing** [comment] 2023-05-14 17:30
Doesn't occur with gesture navigation.
![Screenshot_20230514-132808](https://github.com/Ayagikei/LifeUp/assets/92757918/f3c1c6fe-5a52-47e0-9423-a2d2de09a15c)

**Comment by Ayagikei** [comment] 2023-10-24 15:12
In version v1.93, we tried to replace the implementation class of edge2edge.

If convenient, you can check again to see if the problem exists.

**Comment by UsernamesAreNotMyThing** [comment] 2023-12-25 05:09
Still having this issue.
