### ISSUE TITLE
Number of work sessions between long breaks does not behave correctly

### ISSUE THREAD

**Issue by lrose07** [Ayagikei/LifeUp#5] opened 2021-01-21 19:03 UTC
When using the Pomodoro timer, the number of work sessions between long breaks often does not decrement as work sessions are completed, or will randomly go back to the maximum number of sessions before long break (it will 'say 2 work sessions before long break', and then after completing a short break it will say '4 work sessions before long break').

**Comment by Ayagikei** [comment] 2021-01-22 01:14
Thanks for the feedback.

There is a redundant(?) logic and the cause of that situcation should be it:
when starting the timer, it will check for the last complete time.
If the difference is 4 hours, it will reset the work count.

I will consider remove this logic or make it as a switchable settings.

**Comment by Ayagikei** [comment] 2021-01-26 03:24
Should be fixed in the latest version.(v1.80.7)

**Closed by Ayagikei** 2021-01-26 03:24 UTC
Labels: bug
