### ISSUE TITLE
[bug] Calendar | Task Details view does not refresh after removing subtasks

### ISSUE THREAD

**Issue by SchaffRita** [Ayagikei/LifeUp#11] opened 2021-06-05 09:46 UTC
**🧪 Test Environment**

**LifeUp version**: 1.83.5 (225)
**Android Version**: 6.0.1 / 10
**OS**: MIUI Global 10.2 / Magic UI 4.0.0
* * *
**📝 Steps to Reproduce**

1. Create a new task with the + button
2. Add a subtask
3. Tap on the check mark to save the task
4. Tap on the new task to see the Task View
5. Edit the task using the pencil icon
6. Tap on the gear icon
7. Tap on the trash icon to remove the subtask
8. Tap on OK
9. Save the task
10. Inspect the subtasks in the Task View

✔️ **Expected Results**: the subtask is not visible under the main task.
❌ **Actual Results**: the subtask is still visible under the main task.
💊 **Workaround**: returning to the main screen, then going back to the task shows the correct state of the task.

![image](https://user-images.githubusercontent.com/50463942/120887479-6d83a180-c5f3-11eb-9180-20091cc1fd4d.png)

**Comment by Ayagikei** [comment] 2021-06-05 09:57
Got it!
I successfully reproduced the bug.

I have dealt with the refreshing problem of adding or deleting a single subtask before, but it seems that this problem occurs when there are subtasks deleted to no subtasks.

**Comment by Ayagikei** [comment] 2021-06-16 02:12
This issue has been fixed in the development version (will be released as version 1.82.6 soon).

The reason is that the details page judges that the current task has no subtasks, so the query operation is not performed, and the subtask list of the current page is not processed.

**Closed** 2021-06-23 07:32 UTC
Labels: bug, done
