### ISSUE TITLE
[Bug] When changing between portrait/landscape, app changes back to "tasks" 

### ISSUE THREAD

**Issue by Zazama** [Ayagikei/LifeUp#26] opened 2022-01-25 19:21 UTC
**Describe the bug**
When you are browsing a bottom navigation tab, e.g. the world market, and turn your phone (landscape/portrait mode), the screen changes to the tasks tab instead of staying where you were. Also, the navigation bar doesn't update. 

**To Reproduce**
1. Go to "World" 
2. Turn phone
3. See error

**Expected behavior**
The location should stay the same.

**Screenshots**

![Screenshot_20220125-201904_LifeUp Pro.jpg](https://user-images.githubusercontent.com/7694808/151044479-6df3a6a1-fe42-465c-9a3c-e4cfe1b6b647.jpg)
![Screenshot_20220125-201914_LifeUp Pro.jpg](https://user-images.githubusercontent.com/7694808/151044500-8b51f811-68ee-4402-a1c3-c18a4bde59f3.jpg)

**Environments and Version (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 10
 - Version v1.86.0-rc04 (285)

**Comment by Ayagikei** [comment] 2022-01-26 03:40
Thanks for the bug report!

We will look into it.

**Comment by Ayagikei** [comment] 2022-03-22 07:08
Sorry for forgetting to reply.

We have followed up on this issue, but it is strange that we cannot reproduce the issue in the corresponding version and subsequent versions.

We will close the issue first and reopen it if the issue is confirmed to exist.

**Closed by Ayagikei** 2022-03-22 07:08 UTC
Labels: bug
