### ISSUE TITLE
[Bug] Custom effects on items randomly getting deleted

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [Ayagikei/LifeUp#113] opened 2023-12-17 18:57 UTC
## Describe the bug
Custom effects assigned on some shop items were unexpectedly deleted, seemingly randomly. They weren't shown on the list, not even on the edit page, and were not respected when the item was used.

### To Reproduce
I'm not sure how to reproduce this at this time.

### Environments and Version (please complete the following information):
 - OS: **Android 10** (QDF30.130-42-5-17)
 - Version **1.93.3** (532)

**Comment by Ayagikei** [comment] 2023-12-18 12:49
Hello, there is a reported historical issue, existing in v1.93.0-v1.93.2: due to our incorrect logic on the `disable_use` parameter, if you use use_item to call the API, the use effect of the item will be accidentally lost.

Sorry and regrettable, we are unable to restore items triggered by older versions. You may need to restore them manually.

**This problem should have been fixed in v1.93.3.** We suspect that the problem you are encountering is caused by an old version. You can confirm that the current version no longer introduces the problem of losing the effect of new items.

**Closed as not planned** 2023-12-18 19:08 UTC
Labels: bug
