### ISSUE TITLE
[Bug] Incorrect default language

### ISSUE THREAD

**Issue by Mstik** [Ayagikei/LifeUp#24] opened 2021-12-06 08:46 UTC
**Describe the bug**
Chinese language in Russian localization. 

**To Reproduce**
1. Go to "World (мир) ". There is Chinese words above. 
2. Click on "Create command (создать команду) ". 
3. Scroll down to 'repetition rate (частота повтора) '

**Expected behavior**
Russian words must be here I guess 

**Screenshots**
![Screenshot_2021-12-06-13-26-55-296_net sarasarasa lifeup](https://user-images.githubusercontent.com/95613441/144814771-ceb5057f-82b4-4653-915a-f4398bb90986.jpg)
![Screenshot_2021-12-06-13-26-48-340_net sarasarasa lifeup](https://user-images.githubusercontent.com/95613441/144814782-897d923e-4875-43b9-add9-c33b8c719063.jpg)

**Environments and Version (please complete the following information):**
 - Device: Redmi Note 8T
 - OS: Android 11
 - Version 1. 85.3 (272) 

**Additional context**
-

**Comment by Ayagikei** [comment] 2021-12-06 11:47
**Thanks for the bug report!**

When we switched the language to non-English, the problem was successfully reproduced.

The cause of the problem:
There is a problem with the multi-language default value of the server.

We have configured English for all available languages first (if someone provides a translation, we will replace it with the corresponding translation).
The default language value of the server will be fixed later.

**Closed** 2022-01-10 03:49 UTC
Labels: bug, done
